# Site settings
title: NEXT9
email: next9.kr@gmail.com
url: https://next9.kr
description: "누구나 쉽게 시작하는 디지털 수익 창출 플랫폼</br>디지털 격차를 넘어, 모두의 경제적 자립을 지원합니다"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: NEXT9

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/next9
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/next9-dev

# Build settings
markdown: kramdown
permalink: pretty
